

-- Tipi ENUM
CREATE TYPE condizione AS ENUM (
  'Nuovo',
  'Come Nuovo',
  'Ottime Condizioni',
  'Buone Condizioni',
  'Discrete Condizioni',
  'Cattive Condizioni'
);

CREATE TYPE stato_annuncio AS ENUM (
  'Disponibile',
  'Non Disponibile'
);

CREATE TYPE categoria AS ENUM (
  'Libri di testo',
  'Materiale informatico',
  'Abbigliamento',
  'Strumenti Musicali'
);

CREATE TYPE stato_offerta AS ENUM (
  'Accettata',
  'In Attesa',
  'Rifiutata'
);

CREATE TYPE disponibilita AS ENUM (
  'Disponibile',
  'Occupato',
  'Venduto',
  'Regalato',
  'Scambiato'
);

-- Estensione necessaria per generazione sicura di UUID o password hash
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tabelle
CREATE TABLE UTENTE (
    MATRICOLA CHAR(9),
    USERNAME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    CONSTRAINT LunghezzaFissaMatricola CHECK (MATRICOLA ~ '^[A-Za-z0-9]{9}$'),
    CONSTRAINT UsernameUnique UNIQUE (USERNAME),
    CONSTRAINT EmailUnique UNIQUE (EMAIL),
    CONSTRAINT PK_Matricola PRIMARY KEY (MATRICOLA)
);

CREATE TABLE SEDE (
    IDSEDE BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMESEDE VARCHAR(60) NOT NULL,
    VIA VARCHAR(40) NOT NULL,
    CAP CHAR(5) NOT NULL,
    CITTA VARCHAR(40) NOT NULL,
    CONSTRAINT CAP_Valido CHECK (TRIM(CAP) ~ '^[0-9]{5}$'),
    CONSTRAINT NOMESEDE_Lunghezza CHECK (LENGTH(TRIM(NOMESEDE)) >= 3),
    CONSTRAINT VIA_Lunghezza CHECK (LENGTH(TRIM(VIA)) >= 3),
    CONSTRAINT CITTA_Lunghezza CHECK (LENGTH(TRIM(CITTA)) >= 3),
    CONSTRAINT UnicoNomeSede UNIQUE (NOMESEDE)
);

CREATE TABLE ANNUNCIOREGALO (
    idAnnuncioRegalo BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STATOANNUNCIO stato_annuncio DEFAULT 'Disponibile',
    DESCRIZIONE VARCHAR(255) NOT NULL,
    ORARIOINIZIO TIME(0) NOT NULL,  --Time(0) per evitare frazioni di secondo
    ORARIOFINE TIME(0) NOT NULL,
    FK_idSede BIGINT,
    CONSTRAINT DESCRIZIONEMINIMAREGALO CHECK (LENGTH(TRIM(DESCRIZIONE)) >= 10),
    CONSTRAINT ORARIOINIZIOINFERIOREORARIOFINE CHECK (ORARIOINIZIO < ORARIOFINE),
    CONSTRAINT FK_ANNUNCIO_SEDE FOREIGN KEY (FK_idSede) REFERENCES SEDE(IDSEDE) ON DELETE SET NULL
);

CREATE TABLE ANNUNCIOVENDITA (
    idAnnuncioVendita BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STATOANNUNCIO stato_annuncio DEFAULT 'Disponibile',
    DESCRIZIONE VARCHAR(255) NOT NULL,
    ORARIOINIZIO TIME(0) NOT NULL,
    ORARIOFINE TIME(0) NOT NULL,
    PREZZO NUMERIC(10,2) NOT NULL,
    PREZZOMINIMO NUMERIC(10,2),
    FK_idSede BIGINT,
    CONSTRAINT DESCRIZIONEMINIMAVENDITA CHECK (LENGTH(TRIM(DESCRIZIONE)) >= 10),
    CONSTRAINT CONTROLLOPREZZOMINIMO CHECK (PREZZOMINIMO IS NULL OR PREZZOMINIMO <= PREZZO),
    CONSTRAINT ORARIOINIZIOINFERIOREORARIOFINE CHECK (ORARIOINIZIO < ORARIOFINE),
    CONSTRAINT FK_ANNUNCIO_SEDE FOREIGN KEY (FK_idSede) REFERENCES SEDE(IDSEDE) ON DELETE SET NULL
);

CREATE TABLE ANNUNCIOSCAMBIO (
    idAnnuncioScambio BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STATOANNUNCIO stato_annuncio DEFAULT 'Disponibile',
    DESCRIZIONE VARCHAR(255) NOT NULL,
    ORARIOINIZIO TIME(0) NOT NULL,
    ORARIOFINE TIME(0) NOT NULL,
    NOMIITEMS VARCHAR(255) NOT NULL,
    FK_idSede BIGINT,
    CONSTRAINT DESCRIZIONEMINIMASCAMBIO CHECK (LENGTH(TRIM(DESCRIZIONE)) >= 10),
    CONSTRAINT NOMIITEMSMINIMI CHECK (LENGTH(TRIM(NOMIITEMS)) >= 10),
    CONSTRAINT ORARIOINIZIOINFERIOREORARIOFINE CHECK (ORARIOINIZIO < ORARIOFINE),
    CONSTRAINT FK_ANNUNCIO_SEDE_SCAMBIO FOREIGN KEY (FK_idSede) REFERENCES SEDE(IDSEDE) ON DELETE SET NULL
);

CREATE TABLE RECENSIONE (
    idRecensione BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_idUtenteRecensito CHAR(9) NOT NULL,
    FK_idUtenteRecensore CHAR(9) NOT NULL,
    VOTO INT NOT NULL,
    COMMENTO VARCHAR(255),
    CONSTRAINT FK_RECENSITO FOREIGN KEY (FK_idUtenteRecensito) REFERENCES UTENTE(MATRICOLA) ON DELETE CASCADE,
    CONSTRAINT FK_RECENSORE FOREIGN KEY (FK_idUtenteRecensore) REFERENCES UTENTE(MATRICOLA) ON DELETE CASCADE,
    CONSTRAINT UNICARECENSIONEUTENTE UNIQUE (FK_idUtenteRecensito, FK_idUtenteRecensore),
    CONSTRAINT VOTORANGE CHECK (VOTO BETWEEN 1 AND 5),
    CONSTRAINT NOSELFRECENSIONE CHECK (FK_idUtenteRecensito <> FK_idUtenteRecensore)
);

CREATE TABLE OFFERTASCAMBIO (
    idOffertaScambio BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MESSAGGIO VARCHAR(255) DEFAULT 'Ciao, vorrei scambiare questi oggetti con te',
    STATOOFFERTA stato_offerta NOT NULL DEFAULT 'In Attesa',
    FK_idUtente CHAR(9) NOT NULL,
    FK_idAnnuncioScambio BIGINT NOT NULL,
    ORARIOINIZIO TIME(0) NOT NULL,
    ORARIOFINE TIME(0) NOT NULL,
    CONSTRAINT MESSAGGIOMINIMOSCAMBIO CHECK (LENGTH(TRIM(MESSAGGIO)) >= 10),
    CONSTRAINT UNICAOFFERTASCAMBIOOGGETTOUTENTE UNIQUE (FK_idUtente, FK_idAnnuncioScambio),
    CONSTRAINT ORARIOINIZIOINFERIOREORARIOFINE CHECK (ORARIOINIZIO < ORARIOFINE),
    CONSTRAINT FK_OFFERTASCAMBIO_UTENTE FOREIGN KEY (FK_idUtente) REFERENCES UTENTE(MATRICOLA) ON DELETE CASCADE,
    CONSTRAINT FK_OFFERTASCAMBIO_ANNUNCIOSCAMBIO FOREIGN KEY (FK_idAnnuncioScambio) REFERENCES ANNUNCIOSCAMBIO(idAnnuncioScambio) ON DELETE CASCADE
);

CREATE TABLE OFFERTAVENDITA (
    idOffertaVendita BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MESSAGGIO VARCHAR(255) DEFAULT 'CIAO, VORREI COMPRARE I TUOI OGGETTI',
    STATOOFFERTA stato_offerta NOT NULL DEFAULT 'In Attesa',
    PREZZO NUMERIC(10,2) NOT NULL,
    FK_idUtente CHAR(9) NOT NULL,
    FK_idAnnuncioVendita BIGINT NOT NULL,
    ORARIOINIZIO TIME(0) NOT NULL,
    ORARIOFINE TIME(0) NOT NULL,
    CONSTRAINT MESSAGGIOMINIMOVENDITA CHECK (LENGTH(TRIM(MESSAGGIO)) >= 10),
    CONSTRAINT UNICAOFFERTAVENDITAOGGETTOUTENTE UNIQUE (FK_idUtente, FK_idAnnuncioVendita),
    CONSTRAINT ORARIOINIZIOINFERIOREORARIOFINE CHECK (ORARIOINIZIO < ORARIOFINE),
    CONSTRAINT FK_OFFERTAVENDITA_UTENTE FOREIGN KEY (FK_idUtente) REFERENCES UTENTE(MATRICOLA) ON DELETE CASCADE,
    CONSTRAINT FK_OFFERTAVENDITA_ANNUNCIOVENDITA FOREIGN KEY (FK_idAnnuncioVendita) REFERENCES ANNUNCIOVENDITA(idAnnuncioVendita) ON DELETE CASCADE
);

CREATE TABLE OFFERTAREGALO (
    idOffertaRegalo BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MESSAGGIO VARCHAR(255) DEFAULT 'Ciao, vorrei ricevere il tuo regalo',
    STATOOFFERTA stato_offerta NOT NULL DEFAULT 'In Attesa',
    FK_idUtente CHAR(9) NOT NULL,
    FK_idAnnuncioRegalo BIGINT NOT NULL,
    ORARIOINIZIO TIME(0) NOT NULL,
    ORARIOFINE TIME(0) NOT NULL,
    CONSTRAINT MESSAGGIOMINIMOREGALO CHECK (LENGTH(TRIM(MESSAGGIO)) >= 10),
    CONSTRAINT UNICAOFFERTAREGALOOGGETTOUTENTE UNIQUE (FK_idUtente, FK_idAnnuncioRegalo),
    CONSTRAINT ORARIOINIZIOINFERIOREORARIOFINE CHECK (ORARIOINIZIO < ORARIOFINE),
    CONSTRAINT FK_OFFERTAREGALO_UTENTE FOREIGN KEY (FK_idUtente) REFERENCES UTENTE(MATRICOLA) ON DELETE CASCADE,
    CONSTRAINT FK_OFFERTAREGALO_ANNUNCIOREGALO FOREIGN KEY (FK_idAnnuncioRegalo) REFERENCES ANNUNCIOREGALO(idAnnuncioRegalo) ON DELETE CASCADE
);

CREATE TABLE OGGETTO (
    idOggetto BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CONDIZIONE condizione NOT NULL,
    CATEGORIA categoria NOT NULL,
    DISPONIBILITA disponibilita NOT NULL,
    FK_idUtente CHAR(9) NOT NULL,
    FK_idOffertaScambio BIGINT,
    FK_idAnnuncioRegalo BIGINT,
    FK_idAnnuncioVendita BIGINT,
    FK_idAnnuncioScambio BIGINT,
    CONSTRAINT NOMEOGGETTOLUNGHEZZA CHECK (LENGTH(TRIM(NOME)) >= 6),
    CONSTRAINT FK_OGGETTO_UTENTE FOREIGN KEY (FK_idUtente) REFERENCES UTENTE(MATRICOLA) ON DELETE CASCADE,
    CONSTRAINT FK_OGGETTO_OFFERTASCAMBIO FOREIGN KEY (FK_idOffertaScambio) REFERENCES OFFERTASCAMBIO(idOffertaScambio) ON DELETE SET NULL,
    CONSTRAINT FK_OGGETTO_ANNUNCIOREGALO FOREIGN KEY (FK_idAnnuncioRegalo) REFERENCES ANNUNCIOREGALO(idAnnuncioRegalo) ON DELETE SET NULL,
    CONSTRAINT FK_OGGETTO_ANNUNCIOVENDITA FOREIGN KEY (FK_idAnnuncioVendita) REFERENCES ANNUNCIOVENDITA(idAnnuncioVendita) ON DELETE SET NULL,
    CONSTRAINT FK_OGGETTO_ANNUNCIOSCAMBIO FOREIGN KEY (FK_idAnnuncioScambio) REFERENCES ANNUNCIOSCAMBIO(idAnnuncioScambio) ON DELETE SET NULL
);
